version: '2'

services:
  streetcat_restream:
    build: ./streetcat_restream
    image: TUBIK-corp/streetcat_restream
    container_name: streetcat_restream
    command: python ./streetcat_youtube.py
    volumes:
      - ./conf.py:/conf.py:ro
      - ./client.json:/client.json:ro
      - ./streetcat_viewer/cams.json:/cams.json:ro
      - ./viewer.log:/viewer.log
      - ./auth.json:/auth.json
  web_app:
    build: ./web_app
    image: TUBIK-corp/web_app
    container_name: web_app
    ports:
      - "8080:8080"
    command: python ./web_app.py
    volumes:
      - ./conf.py:/conf.py:ro
      - ./auth.json:/auth.json