version: '2'

services:
  streetcat_restream:
    build: .
    image: TUBIK-corp/streetcat_restream
    container_name: streetcat_restream
    ports:
      - "8080:8080"
    volumes:
      - ./conf.py:/conf.py:ro
      - ./client.json:/client.json:ro
      - ./cams.json:/cams.json:ro
      - ./viewer.log:/viewer.log